root: true

env:
  es6: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

ignorePatterns:
  - dist/
  - test/**/*.js

overrides:
  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/explicit-module-boundary-types":
        - warn
        - allowArgumentsExplicitlyTypedAsAny: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - off

      "@typescript-eslint/no-unsafe-assignment":
        - off

      "@typescript-eslint/no-unsafe-member-access":
        - off

      "@typescript-eslint/no-unsafe-return":
        - off

  - files:
      - "**/__tests__/**/*.spec.{j,t}s?(x)"

    env:
      jest: true
      node: true

    rules:
      "@typescript-eslint/naming-convention":
        - off
      "@typescript-eslint/no-non-null-assertion":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off

  - files:
      - "webpack.config.js"

    env:
      node: true
