# 一行的字符数，如果超过会进行换行，默认为 80
printWidth: 80

# 一个 tab 代表几个空格数，默认为 2
tabWidth: 2

# 是否使用 tab 进行缩进，默认为 false，表示用空格进行缩进
useTabs: false

# 行末是否使用分号，默认为 true
semi: true

# 字符串是否使用单引号，默认为 false，使用双引号
singleQuote: false

# 是否在属性上使用引号 < as-needed(default) | consistent | preserve >
quoteProps: as-needed

# JSX 是否使用单引号，默认为 false
jsxSingleQuote: false

# 是否使用尾逗号，< none | es5(default) | all >
trailingComma: es5

# 对象大括号是否有空格，默认为 true，效果：{ foo: bar }
bracketSpacing: true

# JSX Brackets 是否在同一行
jsxBracketSameLine: false

# 箭头函数单个参数是否包含括号 < always(default) | none >
arrowParens: always

# 格式化文件的范围
# range:

# 代码的解析引擎，默认为 babel，还有 typescript css json markdown vue html yaml 等
# parser: typescript

# Markdown 超长之后是否换行，默认 preserve
proseWrap: preserve

# 行末换行符 < lf(default) | crlf | cr | auto >
endOfLine: lf
