language: node_js
os: linux
dist: bionic
node_js:
  - lts/*
before_script:
  - yarn run build
jobs:
  include:
    - stage: test
      name: "Test in TypeScript"
      script:
        - yarn run test

    - name: "Test in JavaScript"
      script:
        - yarn run test:js

    - name: "Parser self parse test"
      script:
        - yarn run test:parser

stages:
  - name: test
